using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;


namespace RavenCodeGenerators {

[Generator]
public sealed class ComponentPropertyGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // No syntax receiver needed for this simple case
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var compilation = context.Compilation;
        
        var attrSymbol = compilation.GetTypeByMetadataName(
            "ComponentProperty");

        if (attrSymbol is null)
            return;

        foreach (var tree in compilation.SyntaxTrees)
        {
            var semanticModel = compilation.GetSemanticModel(tree);

            foreach (var classDecl in tree.GetRoot()
                     .DescendantNodes()
                     .OfType<ClassDeclarationSyntax>())
            {
                var classSymbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                if (classSymbol is null)
                    continue;

                var attrs = classSymbol.GetAttributes()
                    .Where(a => SymbolEqualityComparer.Default.Equals(
                        a.AttributeClass, attrSymbol));

                if (!attrs.Any())
                    continue;
                

                var source = GenerateClass(classSymbol, attrs);
                context.AddSource(
                    $"{classSymbol.Name}.Components.g.cs",
                    source);
            }
        }
    }

    private static string GenerateClass(
        INamedTypeSymbol classSymbol,
        IEnumerable<AttributeData> attrs)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"namespace {classSymbol.ContainingNamespace};");
        sb.AppendLine();
        sb.AppendLine($"partial class {classSymbol.Name}");
        sb.AppendLine("{");

        foreach (var attr in attrs)
        {
            var name = (string)attr.ConstructorArguments[0].Value!;
            var type = (INamedTypeSymbol)attr.ConstructorArguments[1].Value!;

            sb.AppendLine($@"
    public {type.ToDisplayString()} {name}
    {{
        get => GetData<{type.ToDisplayString()}>(""{name}"");
        set => SetData(""{name}"", value);
    }}");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
} 
}