using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace RavenCodeGenerators;

[Generator]
public sealed class ComponentTypeGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }
    
    public void Execute(GeneratorExecutionContext context)
    {
        var componentBase = context.Compilation.GetTypeByMetadataName("Raven.Engine.Component");
        if (componentBase == null)
            return;

        if (context.SyntaxContextReceiver is not Receiver receiver)
            return;
        
        foreach (var classDecl in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
                continue;

            if (classSymbol.IsAbstract)
                continue;

            if (!InheritsFrom(classSymbol, componentBase))
                continue;

            GenerateTypeProperty(context, classSymbol);
        }
    }

    private static bool InheritsFrom(INamedTypeSymbol symbol, INamedTypeSymbol baseType)
    {
        while (symbol.BaseType != null)
        {
            if (SymbolEqualityComparer.Default.Equals(symbol.BaseType, baseType))
                return true;

            symbol = symbol.BaseType;
        }
        return false;
    }

    private static void GenerateTypeProperty(
        GeneratorExecutionContext context,
        INamedTypeSymbol classSymbol)
    {
        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToString();

        var className = classSymbol.Name;

        if (context.SyntaxContextReceiver is not Receiver receiver) return;
        
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"using Raven.Engine;");
        sb.AppendLine($"using System;");
        sb.AppendLine($"using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    public override Type Type {{ get; set; }} = typeof({className});");
        sb.AppendLine($"    public override String Name {{ get; set; }} = \"{className}\";");
        sb.AppendLine("}");

        context.AddSource($"{className}.Type.g.cs", sb.ToString());
    }

    private sealed class Receiver : ISyntaxContextReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();
        public List<INamedTypeSymbol> CollectedTypes { get; } = new();

        bool InheritsFromTarget(INamedTypeSymbol symbol) => true;
        
        public void OnVisitSyntaxNode(GeneratorSyntaxContext context) {
            
            // Inspect nodes during compilation
            if (context.Node is ClassDeclarationSyntax classDeclaration) {
                var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
                if (symbol != null && !symbol.IsAbstract) {
                    var base_type = symbol.BaseType;
                    // walk inheritance tree
                    while (base_type != null) {
                        if (base_type.Name == "Component") {
                            CollectedTypes.Add(symbol);
                            break;
                        }
                        base_type = base_type.BaseType;
                    }
                    
                }
            }
            
            if (context.Node is ClassDeclarationSyntax cds)
                Candidates.Add(cds);
        }
    }
}
