using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RavenCodeGenerators;

[Generator]
public sealed class ComponentTypeGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var componentBase = context.Compilation.GetTypeByMetadataName("Raven.Engine.Component");
        if (componentBase == null)
            return;

        if (context.SyntaxReceiver is not Receiver receiver)
            return;

        foreach (var classDecl in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
                continue;

            if (classSymbol.IsAbstract)
                continue;

            if (!InheritsFrom(classSymbol, componentBase))
                continue;

            GenerateTypeProperty(context, classSymbol);
        }
    }

    private static bool InheritsFrom(INamedTypeSymbol symbol, INamedTypeSymbol baseType)
    {
        while (symbol.BaseType != null)
        {
            if (SymbolEqualityComparer.Default.Equals(symbol.BaseType, baseType))
                return true;

            symbol = symbol.BaseType;
        }
        return false;
    }

    private static void GenerateTypeProperty(
        GeneratorExecutionContext context,
        INamedTypeSymbol classSymbol)
    {
        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToString();

        var className = classSymbol.Name;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"using Raven.Engine;");
        sb.AppendLine($"using System;");
        sb.AppendLine();
        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    public override Type Type {{ get; set; }} = typeof({className});");
        sb.AppendLine("}");

        context.AddSource($"{className}.Type.g.cs", sb.ToString());
    }

    private sealed class Receiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is ClassDeclarationSyntax cds)
                Candidates.Add(cds);
        }
    }
}
