using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RavenCodeGenerators;
[Generator]
public sealed class EntityUpdatePacketGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not Receiver receiver)
            return;

        var entityInterface =
            context.Compilation.GetTypeByMetadataName("Raven.Engine.Entity");

        if (entityInterface is null)
            return;

        foreach (var classDecl in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (ModelExtensions.GetDeclaredSymbol(model, classDecl) is not INamedTypeSymbol classSymbol)
                continue;

            if (!ImplementsEntity(classSymbol, entityInterface))
                continue;

            if (!classDecl.Modifiers.Any(SyntaxKind.PartialKeyword))
                continue;

            var source = GeneratePartial(classSymbol);
            context.AddSource(
                $"{classSymbol.Name}.update_packet.g.cs",
                source
            );
        }
    }

    private static bool ImplementsEntity(
        INamedTypeSymbol type,
        INamedTypeSymbol entityInterface)
    {
        foreach (var iface in type.AllInterfaces)
            if (SymbolEqualityComparer.Default.Equals(iface, entityInterface))
                return true;

        return false;
    }

    private static string GeneratePartial(INamedTypeSymbol symbol)
    {
        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();
        
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");

        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }
        sb.AppendLine("using System;");
        sb.AppendLine("using Raven.Engine;");
        sb.AppendLine("using Microsoft.Xna.Framework;");
        sb.AppendLine($"partial class {symbol.Name}");
        sb.AppendLine("{");
        sb.AppendLine($"public string name {{ get; set; }} = \"{symbol.Name}\";");
        sb.AppendLine("""
            
            public ChunkPosition _position;
            public ChunkPosition position => _position;
            public void SetPosition(ChunkPosition position) => _position = position;
            
            public ComponentManager Components { get; set; } = new();
            
            public Universe parent_universe { get; set; }
            public Chunk parent_chunk { get; set; }
            
            public Threads.ThreadRequestPacket update_packet { get; set; }
        
            public void Initialize() {
                Components.set_parent(this);
                
                update_packet = new Threads.ThreadRequestPacket(
                    () => Update(),
                    () => this.parent_chunk.task_callback()
                );
            }
            
            public void StabilizeChunkPosition() {
                position.stabilize(Clock.update_thread_delta_ms);                
            }
            
            public void UpdateInterpolatedPosition() {
                position.interpolate(Clock.delta_time_ms);
            }
            
            private void MoveAndSlide(Vector3 movement) => position.MoveAndSlide(movement);
        """);
        sb.AppendLine("}");

        if (ns is not null)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed class Receiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode node)
        {
            if (node is ClassDeclarationSyntax cds)
                Candidates.Add(cds);
        }
    }
}