using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace RavenCodeGenerators;
[Generator]
public sealed class ListManagedClassGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context) {
        var compilation = context.Compilation;

        if (context.SyntaxReceiver is not Receiver receiver)
            return;

        var attrSymbol =compilation.GetTypeByMetadataName(
            "ListManagedClass");

        if (attrSymbol == null)
            return;

        foreach (var classDecl in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
                continue;

            if (!classSymbol.GetAttributes()
                .Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attrSymbol)))
                continue;

            GenerateManager(context, classSymbol);
        }
    }

    private static void GenerateManager(
        GeneratorExecutionContext context,
        INamedTypeSymbol classSymbol)
    {
        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToString();

        var className = classSymbol.Name;
        var managerName = "Manager";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }
        sb.AppendLine($"using System.Collections.Generic;");
        sb.AppendLine($"using System;");
        sb.AppendLine($"");
        sb.AppendLine($"public partial class {className} {{");
        sb.AppendLine($"public static partial class {managerName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static readonly List<{className}> {className.ToLower()}s = new();");
        sb.AppendLine();
        sb.AppendLine($"    public static void Add({className} instance)");
        sb.AppendLine("    {");
        sb.AppendLine($"        {className.ToLower()}s.Add(instance);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static void Remove({className} instance)");
        sb.AppendLine("    {");
        sb.AppendLine($"        {className.ToLower()}s.Remove(instance);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("}");

        context.AddSource($"className.{managerName}.g.cs", sb.ToString());
    }

    private sealed class Receiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is ClassDeclarationSyntax cds &&
                cds.AttributeLists.Count > 0)
            {
                Candidates.Add(cds);
            }
        }
    }
}


[Generator]
public sealed class GuidDictionaryManagedClassGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context) {
        var compilation = context.Compilation;

        if (context.SyntaxReceiver is not Receiver receiver)
            return;

        var attrSymbol =compilation.GetTypeByMetadataName(
            "GuidManagedClass");

        if (attrSymbol == null)
            return;

        foreach (var classDecl in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
                continue;

            if (!classSymbol.GetAttributes()
                .Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attrSymbol)))
                continue;

            GenerateManager(context, classSymbol);
        }
    }

    private static void GenerateManager(
        GeneratorExecutionContext context,
        INamedTypeSymbol classSymbol)
    {
        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToString();

        var className = classSymbol.Name;
        var managerName = "Manager";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }
        sb.AppendLine($"using System.Collections.Generic;");
        sb.AppendLine($"using System.Collections.Concurrent;");
        sb.AppendLine($"using System;");
        sb.AppendLine($"");
        sb.AppendLine($"public partial class {className} {{");
        sb.AppendLine($"public static ConcurrentDictionary<Guid, {className}> All{className}s => {managerName}.{className.ToLower()}s;");
        sb.AppendLine($"public static partial class {managerName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static readonly ConcurrentDictionary<Guid, {className}> {className.ToLower()}s = new();");
        sb.AppendLine();
        sb.AppendLine($"    public static Guid Add({className} instance)");
        sb.AppendLine("    {");
        sb.AppendLine("        var g = Guid.NewGuid();");
        sb.AppendLine($"        {className.ToLower()}s[g] = instance;");
        sb.AppendLine("        return g;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static void Remove(Guid id)");
        sb.AppendLine("    {");
        sb.AppendLine($"        {className.ToLower()}s.Remove(id, out _);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("}");

        context.AddSource($"{className}.{managerName}.g.cs", sb.ToString());
    }

    private sealed class Receiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is ClassDeclarationSyntax cds &&
                cds.AttributeLists.Count > 0)
            {
                Candidates.Add(cds);
            }
        }
    }
}