using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace RavenCodeGenerators;

[Generator]
public sealed class ListManagedGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context) {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context) {
        var compilation = context.Compilation;

        if (context.SyntaxReceiver is not Receiver receiver)
            return;

        var attrSymbol =compilation.GetTypeByMetadataName(
            "ListManaged");

        if (attrSymbol == null)
            return;

        foreach (var classDecl in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
                continue;

            if (!classSymbol.GetAttributes()
                .Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attrSymbol)))
                continue;

            GenerateManager(context, classSymbol);
        }
    }

    private static void GenerateManager(
        GeneratorExecutionContext context,
        INamedTypeSymbol classSymbol)
    {
        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToString();

        var className = classSymbol.Name;
        var managerName = "Manager";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }
        sb.AppendLine($"using System.Collections.Generic;");
        sb.AppendLine($"using System;");
        sb.AppendLine($"");
        sb.AppendLine($"public partial class {className} {{");
        sb.AppendLine($"public static partial class {managerName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static readonly List<{className}> {className.ToLower()}s = new();");
        sb.AppendLine();
        sb.AppendLine($"    public static void Add({className} instance)");
        sb.AppendLine("    {");
        sb.AppendLine($"        {className.ToLower()}s.Add(instance);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static void Remove({className} instance)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if ({className.ToLower()}s.Contains(instance))");
        sb.AppendLine($"            {className.ToLower()}s.Remove(instance);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("}");

        context.AddSource($"{ns}.{className}.{managerName}.g.cs", sb.ToString());
    }

    private sealed class Receiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is ClassDeclarationSyntax cds) {
                Candidates.Add(cds);
            }
        }
    }
}

[Generator]
public sealed class GuidDictionaryManagedGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context) {
        var compilation = context.Compilation;

        if (context.SyntaxReceiver is not Receiver receiver)
            return;

        var attrSymbol =compilation.GetTypeByMetadataName(
            "GuidManaged");

        if (attrSymbol == null)
            return;

        foreach (var classDecl in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
                continue;

            if (!classSymbol.GetAttributes()
                .Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attrSymbol)))
                continue;

            GenerateManager(context, classSymbol);
        }
    }

    private static void GenerateManager(
        GeneratorExecutionContext context,
        INamedTypeSymbol classSymbol)
    {
        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToString();

        var className = classSymbol.Name;
        var managerName = "Manager";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }
        sb.AppendLine($"using System.Collections.Generic;");
        sb.AppendLine($"using System.Collections.Concurrent;");
        sb.AppendLine($"using System;");
        sb.AppendLine($"");
        sb.AppendLine($"public partial class {className} {{");
        sb.AppendLine($"public static ConcurrentDictionary<Guid, {className}> All{className}s => {managerName}.{className.ToLower()}s;");
        sb.AppendLine($"public Guid GUID;");
        sb.AppendLine();
        sb.AppendLine($"public static partial class {managerName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static readonly ConcurrentDictionary<Guid, {className}> {className.ToLower()}s = new();");
        sb.AppendLine();
        sb.AppendLine($"    public static Guid Add({className} instance)");
        sb.AppendLine("    {");
        sb.AppendLine("        var g = Guid.NewGuid();");
        sb.AppendLine($"       {className.ToLower()}s[g] = instance;");
        sb.AppendLine($"       {className.ToLower()}s[g].GUID = g;");
        sb.AppendLine("        return g;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static void Remove(Guid id)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if ({className.ToLower()}s.ContainsKey(id))");
        sb.AppendLine($"            {className.ToLower()}s.Remove(id, out _);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("}");

        context.AddSource($"{ns}.{className}.{managerName}.g.cs", sb.ToString());
    }
    
    private sealed class Receiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is ClassDeclarationSyntax cds) {
                Candidates.Add(cds);
            }
        }
    }
}


[Generator]
public sealed class HashSetManagedGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context) {
        var compilation = context.Compilation;

        if (context.SyntaxReceiver is not Receiver receiver)
            return;

        var attrSymbol =compilation.GetTypeByMetadataName(
            "HashSetManaged");

        if (attrSymbol == null)
            return;

        foreach (var classDecl in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
                continue;

            if (!classSymbol.GetAttributes()
                .Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attrSymbol)))
                continue;

            GenerateManager(context, classSymbol);
        }
    }

    private static void GenerateManager(
        GeneratorExecutionContext context,
        INamedTypeSymbol classSymbol)
    {
        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToString();

        var className = classSymbol.Name;
        var managerName = "Manager";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }
        sb.AppendLine($"using System.Collections.Generic;");
        sb.AppendLine($"using System.Collections.Concurrent;");
        sb.AppendLine($"using System;");
        sb.AppendLine($"");
        sb.AppendLine($"public partial class {className} {{");
        sb.AppendLine($"public static HashSet<{className}> All{className}s => {managerName}.{className.ToLower()}s;");
        sb.AppendLine($"public static partial class {managerName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static readonly HashSet<{className}> {className.ToLower()}s = new();");
        sb.AppendLine();
        sb.AppendLine($"    public static void Add({className} instance)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (!{className.ToLower()}s.Contains(instance))");
        sb.AppendLine($"            {className.ToLower()}s.Add(instance);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static void Remove({className} instance)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if ({className.ToLower()}s.Contains(instance))");
        sb.AppendLine($"            {className.ToLower()}s.Remove(instance);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("}");

        context.AddSource($"{ns}.{className}.{managerName}.HashSet.g.cs", sb.ToString());
    }
    
    private sealed class Receiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is ClassDeclarationSyntax cds) {
                Candidates.Add(cds);
            }
        }
    }
}


[Generator]
public sealed class ManagedPollingLoopGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context) {
        var compilation = context.Compilation;

        if (context.SyntaxReceiver is not Receiver receiver)
            return;

        var attrSymbol =compilation.GetTypeByMetadataName(
            "ManagedPollingLoop");

        if (attrSymbol == null)
            return;

        foreach (var classDecl in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
                continue;

            if (!classSymbol.GetAttributes()
                .Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attrSymbol)))
                continue;

            GenerateManager(context, classSymbol);
        }
    }

    private static void GenerateManager(
        GeneratorExecutionContext context,
        INamedTypeSymbol classSymbol)
    {
        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToString();

        var className = classSymbol.Name;
        var managerName = "Manager";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }
        sb.AppendLine($"using System.Collections.Generic;");
        sb.AppendLine($"using System.Collections.Concurrent;");
        sb.AppendLine($"using System.Diagnostics;");
        sb.AppendLine($"using System.Threading;");
        sb.AppendLine($"using System;");
        sb.AppendLine($"");
        sb.AppendLine($"public partial class {className} {{");
        sb.AppendLine($"public static HashSet<{className}> All{className}s => {managerName}.{className.ToLower()}s;");
        sb.AppendLine($"public static partial class {managerName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static readonly HashSet<{className}> {className.ToLower()}s = new();");
        sb.AppendLine();
        sb.AppendLine($"    private static Action UpdateAction;");
        sb.AppendLine($"    private static Clock.TickRateWatcher TickRateWatcher = new();");
        sb.AppendLine($"    private static Stopwatch loop_stopwatch;");
        sb.AppendLine();
        sb.AppendLine($"    internal static double poll_rate {{ get; set; }} = 1000.0;");
        sb.AppendLine($"    public static TimeSpan poll_goal_time => new TimeSpan((long)(10000 * (1000.0/poll_rate)));");
        sb.AppendLine($"    public static double PollRate => poll_rate;");
        sb.AppendLine($"    public static double TicksPerSecond => TickRateWatcher.TicksPerSecond;");
        sb.AppendLine();
        sb.AppendLine("""
                            private static void StartControlPollingThread(string name, Action update_action) {{
                                UpdateAction = update_action;
                                Threads.StartTask(name, TimedUpdateLoop);
                            }}
                      """);
        sb.AppendLine("""
                            private static void TimedUpdateLoop() {
                                loop_stopwatch = Stopwatch.StartNew();
                                long frame_start = 0;
                                
                                double elapsed_ms() => (loop_stopwatch.ElapsedTicks - frame_start) * 1000.0 / (double)Stopwatch.Frequency;
                                double remaining_ms() => (poll_goal_time.TotalMilliseconds - elapsed_ms());
                        
                                while (!State.wait_for_init) ;
                                while (!Threads.IsCancellationRequested) {
                                    frame_start = loop_stopwatch.ElapsedTicks;
                                    
                                    UpdateAction();
                                    
                                    if (remaining_ms() > 1.0) {
                                        var ms = remaining_ms(); 
                                        Thread.Sleep((int)(ms - 0.5) >= 0 ? (int)(ms - 0.5) : 0);  
                                    }
                                    while (remaining_ms() > 0.0 && !Threads.IsCancellationRequested) {
                                        Thread.SpinWait(1);
                                    }
                                    
                                    TickRateWatcher.PollRateUpdate(elapsed_ms());
                                }
                            }
                        """);
        sb.AppendLine();
        sb.AppendLine($"    public static void Add({className} instance)");
        sb.AppendLine("    {");
        sb.AppendLine($"        {className.ToLower()}s.Add(instance);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static void Remove({className} instance)");
        sb.AppendLine("    {");
        sb.AppendLine($"        {className.ToLower()}s.Remove(instance);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("}");

        context.AddSource($"{ns}.{className}.{managerName}.HashSet.g.cs", sb.ToString());
    }
    
    private sealed class Receiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is ClassDeclarationSyntax cds) {
                Candidates.Add(cds);
            }
        }
    }
}