using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RavenCodeGenerators;
[Generator]
public sealed class SceneExtraGenerator : ISourceGenerator {
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }
    
    
    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not Receiver receiver)
            return;

        var entityInterface =
            context.Compilation.GetTypeByMetadataName("Raven.Engine.Worlds.IWorld");

        if (entityInterface is null)
            return;

        foreach (var classDecl in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (ModelExtensions.GetDeclaredSymbol(model, classDecl) is not INamedTypeSymbol classSymbol)
                continue;

            if (!ImplementsEntity(classSymbol, entityInterface))
                continue;

            if (!classDecl.Modifiers.Any(SyntaxKind.PartialKeyword))
                continue;

            var source = GeneratePartial(classSymbol);
            context.AddSource(
                $"{classSymbol.Name}.extra.g.cs",
                source
            );
        }
    }

    private static bool ImplementsEntity(
        INamedTypeSymbol type,
        INamedTypeSymbol entityInterface)
    {
        foreach (var iface in type.AllInterfaces)
            if (SymbolEqualityComparer.Default.Equals(iface, entityInterface))
                return true;

        return false;
    }
    
    private static string GeneratePartial(INamedTypeSymbol symbol)
    {
        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();
        
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");

        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }
        sb.AppendLine("using System;");
        sb.AppendLine("using Raven.Engine;");
        sb.AppendLine("using Raven.Engine.Worlds;");
        sb.AppendLine("using Microsoft.Xna.Framework;");
        sb.AppendLine($"partial class {symbol.Name}");
        sb.AppendLine("{");
        sb.AppendLine("""
            public bool CurrentlyStabilizing = false;
        """);
        sb.AppendLine("}");

        if (ns is not null)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed class Receiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode node)
        {
            if (node is ClassDeclarationSyntax cds)
                Candidates.Add(cds);
        }
    }
}