using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RavenCodeGenerators;

[Generator]
public sealed class IUIFormBoilerplateGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not Receiver receiver)
            return;

        var entityInterface =
            context.Compilation.GetTypeByMetadataName("Raven.UI.IUIForm");

        if (entityInterface is null)
            return;

        foreach (var classDecl in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (ModelExtensions.GetDeclaredSymbol(model, classDecl) is not INamedTypeSymbol classSymbol)
                continue;

            if (!ImplementsEntity(classSymbol, entityInterface))
                continue;

            if (!classDecl.Modifiers.Any(SyntaxKind.PartialKeyword))
                continue;

            var source = GeneratePartial(classSymbol);
            context.AddSource(
                $"{classSymbol.Name}.boilerplate.g.cs",
                source
            );
        }
    }

    private static bool ImplementsEntity(
        INamedTypeSymbol type,
        INamedTypeSymbol entityInterface)
    {
        foreach (var iface in type.AllInterfaces)
            if (SymbolEqualityComparer.Default.Equals(iface, entityInterface))
                return true;

        return false;
    }

    private static string GeneratePartial(INamedTypeSymbol symbol)
    {
        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();
        
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");

        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }
        
        sb.AppendLine("using System;");
        sb.AppendLine("using Raven.Engine;");
        sb.AppendLine("using Microsoft.Xna.Framework;");
        sb.AppendLine("using Microsoft.Xna.Framework.Graphics;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Raven.Engine.Collision;");
        sb.AppendLine("using Raven.Graphics.Drawing2D;");
        sb.AppendLine("using Raven.Engine.Collision.Shapes2D;");
        sb.AppendLine("using Raven.UI;");
        sb.AppendLine("using Raven.UI;");
        sb.AppendLine($"partial class {symbol.Name}");
        sb.AppendLine("{");
        sb.AppendLine($$"""
                        public IUIForm parent_form { get; set; }
                        bool is_child => parent_form != null;
                        
                        public string name => _name; 
                        string _name = "{{symbol.Name}}";
                        public void change_name(string name) { _name = name; }
                        
                        public string text => _text;
                        private string _text = "{{symbol.Name}}";
                        private Vector2i text_size; 
                        
                        public Vector2i position { get; set; } = Vector2i.Zero;
                        public Vector2i size { get; set; } = Vector2i.One * 64;
                        
                        public Vector2i absolute_position => is_child ? parent_form.absolute_position + parent_form.client_top_left + position : position;
                        
                        public ui_layer_state layer_state { get; set; } = ui_layer_state.floating;
                        public FormAnchor anchor { get; set; } = FormAnchor.TopLeft;
                        
                        public bool has_focus { get; set; } = false;
                        public bool visible => _visible;
                        bool _visible = true;
                        
                        public void hide() { _visible = false; }
                        public void show() { _visible = true; }
                        public void toggle_visibility() { _visible = !_visible; }
                        public void toggle_visibility(bool toggle) { _visible = toggle; }
                        
                        public Vector2i top_left => position;
                        public Vector2i bottom_right => position + size;
                        public Vector2i top_right => position + size.OnlyX();
                        public Vector2i bottom_left => position + size.OnlyY();
                        
                        public bool mouse_over => (mouse_interactions.Count > 0) && top_of_mouse_stack;
                        public bool top_of_mouse_stack { get; set; } = false;
                        public List<string> mouse_interactions => _mouse_interactions;
                        List<string> _mouse_interactions = new List<string>();
                        
                        public List<IUIForm> subforms { get; set; } = new List<IUIForm>();
                        
                        public RenderTarget2D client_area => _client_area;
                        private RenderTarget2D _client_area;
                        public bool use_internal_rendering => _client_area != null && client_size.X > 0 && client_size.Y > 0;
                        
                        public Dictionary<string, Collision2D.Shape2D> collision => _collision;
                        Dictionary<string, Collision2D.Shape2D> _collision = new Dictionary<string, Collision2D.Shape2D>();
                        
                        public void change_text(string text) {
                            this._text = text;
                            text_size = Draw2D.measure_string_profont_int(text);
                        }
                        
                        public void reconfigure_client_area() {
                            _client_area = new RenderTarget2D(State.graphics_device, client_size.X, client_size.Y);
                            _collision.Add("client_area", new BoundingBox2D(absolute_position, size));
                        }
                        
                        public void add_subform(IUIForm subform) {
                            subform.parent_form = this;
                            subforms.Add(subform);
                        }
                        
                        public int get_form_depth() {
                            int d = 0;
                            IUIForm current = this;
                            while (current.parent_form != null) {
                                current = current.parent_form;
                                d++;
                            }
                            return d;
                        }
                        
                        public void recurse_all_subforms(Action<IUIForm> run_on_all_subforms) {
                            for (var index = 0; index < subforms.Count; index++) {
                                run_on_all_subforms(subforms[index]);
                                recurse_all_subforms(subforms[index], run_on_all_subforms);
                            }
                        }
                        
                        void recurse_all_subforms(IUIForm parent, Action<IUIForm> run_on_all_subforms) {
                            for (var index = 0; index < parent.subforms.Count; index++) {
                                run_on_all_subforms(parent.subforms[index]);
                                recurse_all_subforms(parent.subforms[index], run_on_all_subforms);
                            }
                        }
                        
                        public string list_subforms() {
                            return UIStandard.list_subforms(subforms);
                        }
                        
                        void setup(int X, int Y, int width, int height) {
                            this.position = new Vector2i(X, Y);
                            this.size = new Vector2i(width, height);
                            
                            _collision.Add("form", new BoundingBox2D(absolute_position, size));
                            
                        }
                        
                        public void update_collision() {
                            if (_collision.ContainsKey("form")) {
                                if (is_child) {
                                    ((BoundingBox2D)_collision["form"]).set(absolute_position, absolute_position + size);
                                } else {
                                    ((BoundingBox2D)_collision["form"]).set(top_left, bottom_right);
                                }
                            }
                        
                            if (_collision.ContainsKey("client_area")) 
                                ((BoundingBox2D)_collision["client_area"]).set(absolute_position + client_top_left, absolute_position + client_top_left + client_size);
                            
                        }
                        
                        public bool test_mouse() {
                            return UIStandard.test_mouse(ref _collision, ref _mouse_interactions);
                        }
                        """);
        sb.AppendLine("}");

        if (ns is not null)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed class Receiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode node)
        {
            if (node is ClassDeclarationSyntax cds)
                Candidates.Add(cds);
        }
    }
}