<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RollForward>Major</RollForward>
        <PublishReadyToRun>false</PublishReadyToRun>
        <TieredCompilation>false</TieredCompilation>
    </PropertyGroup>
    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Icon.ico</ApplicationIcon>
    </PropertyGroup>
    <PropertyGroup>
        <!-- Tells Rider and the compiler to analyze code for AOT compatibility -->
        <IsAotCompatible>true</IsAotCompatible>

        <!-- Treats AOT and Trim warnings as errors so you can't accidentally break it -->
        <IllinkTreatWarningsAsErrors>true</IllinkTreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup>
        <PublishAot>true</PublishAot>
    </PropertyGroup>
    <ItemGroup>
        <None Remove="Icon.ico"/>
        <None Remove="Icon.bmp"/>
        <None Update="Content\ProFontWindows.ttf">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Content\Mouse.ttf">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Content\BitstromWeraNerdFontMono-Regular.ttf">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Icon.ico">
            <LogicalName>Icon.ico</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="Icon.bmp">
            <LogicalName>Icon.bmp</LogicalName>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5" />
        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5" />
        <PackageReference Include="MoonSharp" Version="3.0.0-beta.1" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Raven.CodeGenerators\Raven.CodeGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Raven\Raven.csproj"/>
    </ItemGroup>
    <Target Name="ZipPublishOutput" AfterTargets="Publish">
    <PropertyGroup>
        <ZipOutputFileName>$(MSBuildProjectDirectory)\..\publish_ravenedit.zip</ZipOutputFileName>
    </PropertyGroup>
    <ZipDirectory SourceDirectory="$(PublishDir)" DestinationFile="$(ZipOutputFileName)" Overwrite="true" />
</Target>
</Project>