using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using Raven.Engine.Controls;

using Raven.Engine;
using Raven.Graphics.Drawing2D;

//TODO finish no overdraw shader, should be a cake walk. use it to make shadows not overlap. idk why spritebatch opaque raster mode ain't work tho 

//TODO should only block binds when a SUBform has focus, and subform focus should be removed on clicking the empty space in a window
// still also need to add tab selection/indexing hehe 

//TODO add window size lower bounds, prolly like 64x64

//TODO add alt tab in click focus mode??

//TODO add alt+click move/resize

//TODO fix the FUCKIN console add scrolling make it render not everything holy shit limit the fucking scrollback

//TODO try SDL_ttf for font rendering

//TODO add stripe shader and ManagedEffect/Draw2D code for it
// also add polkadot shader and dithered gradient shader
// could be fun to allow the user to theme elements that use checkerboards to use stripes/dots instead
// already want to allow full color selection so
    
//TODO add SoundFlow state information & audio adapters to debug display

//TODO add system to attach context menus to UIForms

//TODO add a TabbedPanel UI form then use it to start building the inspector
// also re-add frame probes and add some cool frame profiling stats to it 

//TODO finish implementing display mode toggle hotkeys (F10,11,12)

//TODO clean up gvar names and add categorization prefixes to default engine gvars
// e_ for engine, g_ for graphics, i_ for input? 
// also gvars.add_newline(); might be handy depending on how big the config gets

//TODO modify window manager to take mouse input (and keyboard? should be doable through Watcher classes) through functions, to make it possible to instantiate them and
// do like DOOM3 style in-game computer screen what you can click

//TODO add current scene state saving/loading system (even just some JSON trash idk)
// needs to have universal structure for Entity objects and their components, but variable layout depending on scene type for the ScenePositionInfo and general structure

//TODO implement loading, reloading, and creating objects via CS-scripts. 
// maybe each entity can get a .cs file of which a blank is autogenerated and saved to disk by the engine before being opened for editing

//TODO add saving/loading binds based on a template and locked file layout a la how gvars do it 

//TODO implement proper handling for keeping windows positioned on screen when the window size changes
// it kinda happens if you interact with a window but it should probably also happen when the game size changes

//TODO fix high freq audio loop now that I actually understand what's goin on
//TODO function queue for the high freq audio loop
// instead of doing multiple things per loop, do one thing from the top of a queue to try to keep performance as lockstep as possible
// (ALAP)

//TODO build new broad/narrow solvers for collision detection and resolution
// Start with a broad phase solver which runs on a thread that constantly checks a ConcurrentQueue for entities to test for collisions,
// this solver will be unique to each scene. It will run a method in the Scene object that adds Entities to a second ConcurrentQueue,
// for the narrow phase to solve. The narrow phase will then call a callback method with information about the collisions or lack thereof.
// Narrow phase also needs to be able to add objects back into itself if their movement is extreme enough that it changes their octree positions
// In this engine, I want support for high speed projectiles, so swept collisions are used, and narrow phase will be multi-step
// if there is a collision with an object, the object will be given the choice to either EPA directly out, EPA out then move tangential to
// the impact normal by the distance that it penetrated the wall, or, if the entity requires it, run custom collision code 

//TODO turn Raven into a basic scene editor with the ability to save and load 
// use a combination of brush-based objects and imported mesh static objects

//TODO build a UI development tool

//TODO add basic physical interactions; impulse and transfer of force, angular momentum, basic friction (complex friction?? I like threading), etc. more fancy source-like stuff would be v nice
// not like a spring is particularly hard to understand, but making 4 of them work on the same mass at the same time is uhhhh spooky
// least I got a fixed deterministic timestep, but still like how da fuck does babby integrate
     
//TODO idk maybe implement video playback? could be useful for japes at least

namespace Raven;

public class RavenGame : Game {
    private GraphicsDeviceManager _graphics;

    public RavenGame() {
        _graphics = new GraphicsDeviceManager(this);
        Content.RootDirectory = "Content";
        
        _graphics.PreferredBackBufferWidth = 1280;
        _graphics.PreferredBackBufferHeight = 720;
        
        IsMouseVisible = true;
        Window.AllowUserResizing = true;
        
    }

    protected override void Initialize() {
        State.Initialize(this, Content, _graphics, Window);
        base.Initialize();
    }

    protected override void LoadContent() {
        State.Load(Content);
    }
    
    protected override void Update(GameTime gameTime) {
        if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed ||
            Keyboard.GetState().IsKeyDown(Keys.Escape)) {
            Exit();
        }
        
        State.UpdateGraphics(gameTime);
        
        base.Update(gameTime);
    }
    
    protected override void Draw(GameTime gameTime) {
        GraphicsDevice.Clear(Color.CornflowerBlue);
        
        State.Render();
        
        Clock.FrameRateUpdate(gameTime.ElapsedGameTime.TotalMilliseconds);
        base.Draw(gameTime);
    }
}