namespace Raven;
internal class TODO {
//TODO add a TabbedPanel UI form then use it to start building the inspector
// also re-add frame probes and add some cool frame profiling stats to it 

//TODO report how many scroll wheel ticks have happened in the last frame

//TODO right click system where a menu can be connected to a collision
//TODO drop down selection menu

//fuck I'm doing it again aren't I
//oh well at least this is shaping up to be my best pointless UI toolkit

//TODO Brush entity which can take different basic shapes

//TODO add IUIForm anchor/dock systems (aaaaaaaahhhHHH)
    
//TODO move sun/moon based lighting into its own file why is that still in State fuckin nuts
// also still need to add a sun/moon

//TODO attempt to render a scene within a scene, and if that works, attempt to set up and then automate HL2 3D skyboxen

//TODO add the ability to make a bindwatcher simply ignore all bind disabling efforts, to allow for a set of global utility hotkeys

//TODO start separating out the funny test textures into Cassowary to make sure that the two mgcbs won't fuck each other big style
// basically keep Raven just having normal Raven engine stuff, so that once it becomes an editor, Cass can be excluded from versioning
// and only used locally for short scale testing bullshit

//TODO finish no-overdraw shader, should be a cake walk. use it to make shadows not overlap. idk why spritebatch opaque raster mode ain't work tho 
//TODO finish animated texture code + shader
//TODO add stripe shader and ManagedEffect/Draw2D code for it
// also add polkadot shader and dithered gradient shader
// could be fun to allow the user to theme elements that use checkerboards to use stripes/dots instead
// already want to allow full color selection so

//TODO should only block binds when a SUBform has focus, and subform focus should be removed on clicking the empty space in a window
// still also need to add tab selection/indexing hehe 

//TODO add window size lower bounds, prolly like 64x64, plus better keep-on-screen mechanics

//TODO add alt+click move/resize

//TODO fix the FUCKIN console add scrolling make it render not everything holy shit limit the fucking scrollback

//TODO try SDL_ttf for font rendering

//TODO make a better tool for managing a TODO list
    
//TODO add SoundFlow state information & audio adapters to debug display

//TODO add system to attach context menus to UIForms

//TODO finish implementing display mode toggle hotkeys (F10,11,12)

//TODO add the rest of the XInput support
// make sure that binds work as both digital and analog regardless of the type of input 

//TODO clean up gvar names and add categorization prefixes to default engine gvars
// e_ for engine, g_ for graphics, i_ for input? 
// also gvars.add_newline(); might be handy depending on how big the config gets

//TODO modify window manager to take mouse input (and keyboard? should be doable through Watcher classes) through functions, to make it possible to instantiate them and
// do like DOOM3 style in-game computer screen what you can click

//TODO add current scene state saving/loading system (even just some JSON trash idk)
// needs to have universal structure for Entity objects and their components, but variable layout depending on scene type for the ScenePositionInfo and general structure

//TODO implement loading, reloading, and creating objects via CS-scripts. 
// maybe each entity can get a .cs file of which a blank is autogenerated and saved to disk by the engine before being opened for editing

//TODO add saving/loading binds based on a template and locked file layout a la how gvars do it 

//TODO implement proper handling for keeping windows positioned on screen when the window size changes
// it kinda happens if you interact with a window but it should probably also happen when the game size changes

//TODO fix high freq audio loop now that I actually understand what's goin on
//TODO function queue for the high freq audio loop
// instead of doing multiple things per loop, do one thing from the top of a queue to try to keep performance as lockstep as possible
// (ALAP)

//TODO build new broad/narrow solvers for collision detection and resolution
// Start with a broad phase solver which runs on a thread that constantly checks a ConcurrentQueue for entities to test for collisions,
// this solver will be unique to each scene. It will run a method in the Scene object that adds Entities to a second ConcurrentQueue,
// for the narrow phase to solve. The narrow phase will then call a callback method with information about the collisions or lack thereof.
// Narrow phase also needs to be able to add objects back into itself if their movement is extreme enough that it changes their octree positions
// In this engine, I want support for high speed projectiles, so swept collisions are used, and narrow phase will be multi-step
// if there is a collision with an object, the object will be given the choice to either EPA directly out, EPA out then move tangential to
// the impact normal by the distance that it penetrated the wall, or, if the entity requires it, run custom collision code 

//TODO turn Raven into a basic scene editor with the ability to save and load 
// use a combination of brush-based objects and imported mesh static objects

//TODO build a UI development tool

//TODO add basic physical interactions; impulse and transfer of force, angular momentum, basic friction (complex friction?? I like threading), etc. more fancy source-like stuff would be v nice
// not like a spring is particularly hard to understand, but making 4 of them work on the same mass at the same time is uhhhh spooky
// least I got a fixed deterministic timestep, but still like how da fuck does babby integrate
     
//TODO idk maybe implement video playback? could be useful for japes at least

}